const language = {
  English: {
    search: "search",
    home: "Home",
    movies: "Movies",
    shows: "Shows",
    popular: "Popular",
    trending: "Trending",
    profile: "Profile",
    settings: "Settings",
    logout: "Logout",
    welcome: "Welcome",
    play: "Play",
    pause: "Pause",
    watchNow: "Watch Now",
    signIn: "Sign In",
    signUp: "Sign Up",
    gptSearchPlaceholder: "What would you like to watch today?",
    GPTSearch: "GPT Search",
    NowPlaying: "Now Playing",
    Popular: "Popular",
    TopRated: "Top-Rated",
    Upcoming: "Upcoming",
    dontHaveAccount: "Don't have an account? Sign Up",
    alreadyHaveAccount: "Already have an account? Sign In",
  },
  Hindi: {
    search: "खोज",
    home: "होम",
    movies: "फिल्में",
    shows: "शो",
    popular: "लोकप्रिय",
    trending: "प्रवृत्तियां",
    profile: "प्रोफ़ाइल",
    settings: "सेटिंग्स",
    logout: "लॉगआउट",
    welcome: "स्वागत है",
    play: "चलाएं",
    pause: "रोकें",
    watchNow: "अब देखें",
    signIn: "साइन इन करें",
    signUp: "साइन अप करें",
    gptSearchPlaceholder: "आज आप क्या देखना चाहेंगे?",
    GPTSearch: "GPT खोज",
    NowPlaying: "अब चल रहा है",
    Popular: "लोकप्रिय",
    TopRated: "शीर्ष रेटेड",
    Upcoming: "आगामी",
    dontHaveAccount: "खाता नहीं है? साइन अप करें",
    alreadyHaveAccount: "पहले से खाता है? साइन इन करें",
  },
  Chinese: {
    search: "搜索",
    home: "主页",
    movies: "电影",
    shows: "节目",
    popular: "流行",
    trending: "趋势",
    profile: "个人资料",
    settings: "设置",
    logout: "登出",
    welcome: "欢迎",
    play: "播放",
    pause: "暂停",
    watchNow: "现在观看",
    signIn: "登录",
    signUp: "注册",
    gptSearchPlaceholder: "今天你想看什么？",
    GPTSearch: "GPT 搜索",
    NowPlaying: "现在播放",
    Popular: "流行",
    TopRated: "顶级评分",
    Upcoming: "即将到来",
    dontHaveAccount: "还没有账户？注册",
    alreadyHaveAccount: "已有账户？登录",
  },
  Spanish: {
    search: "buscar",
    home: "Inicio",
    movies: "Películas",
    shows: "Espectáculos",
    popular: "Popular",
    trending: "Tendencias",
    profile: "Perfil",
    settings: "Configuración",
    logout: "Cerrar sesión",
    welcome: "Bienvenido",
    play: "Reproducir",
    pause: "Pausa",
    watchNow: "Ver ahora",
    signIn: "Iniciar sesión",
    signUp: "Registrarse",
    gptSearchPlaceholder: "¿Qué te gustaría ver hoy?",
    GPTSearch: "GPT búsqueda",
    NowPlaying: "Ahora en reproducción",
    Popular: "Popular",
    TopRated: "Mejor valorados",
    Upcoming: "Próximos",
    dontHaveAccount: "¿No tienes cuenta? Regístrate",
    alreadyHaveAccount: "¿Ya tienes cuenta? Iniciar sesión",
  },
  German: {
    search: "suchen",
    home: "Startseite",
    movies: "Filme",
    shows: "Shows",
    popular: "Beliebt",
    trending: "Trendig",
    profile: "Profil",
    settings: "Einstellungen",
    logout: "Abmelden",
    welcome: "Willkommen",
    play: "Abspielen",
    pause: "Pause",
    watchNow: "Jetzt ansehen",
    signIn: "Anmelden",
    signUp: "Registrieren",
    gptSearchPlaceholder: "Was möchten Sie heute ansehen?",
    GPTSearch: "GPT-Suche",
    NowPlaying: "Jetzt läuft",
    Popular: "Beliebt",
    TopRated: "Top-bewertet",
    Upcoming: "Bevorstehend",
    dontHaveAccount: "Noch keinen Account? Registrieren",
    alreadyHaveAccount: "Haben Sie bereits ein Konto? Anmelden",
  },
  Russian: {
    search: "поиск",
    home: "Главная",
    movies: "Фильмы",
    shows: "Шоу",
    popular: "Популярное",
    trending: "Тренды",
    profile: "Профиль",
    settings: "Настройки",
    logout: "Выйти",
    welcome: "Добро пожаловать",
    play: "Играть",
    pause: "Пауза",
    watchNow: "Смотреть сейчас",
    signIn: "Войти",
    signUp: "Зарегистрироваться",
    gptSearchPlaceholder: "Что бы вы хотели посмотреть сегодня?",
    GPTSearch: "GPT поиск",
    NowPlaying: "Сейчас идет",
    Popular: "Популярное",
    TopRated: "Топ-рейтинг",
    Upcoming: "Предстоящие",
    dontHaveAccount: "Нет аккаунта? Зарегистрироваться",
    alreadyHaveAccount: "Уже есть аккаунт? Войти",
  },
  French: {
    search: "rechercher",
    home: "Accueil",
    movies: "Films",
    shows: "Spectacles",
    popular: "Populaire",
    trending: "Tendances",
    profile: "Profil",
    settings: "Paramètres",
    logout: "Se déconnecter",
    welcome: "Bienvenue",
    play: "Lire",
    pause: "Pause",
    watchNow: "Regarder maintenant",
    signIn: "Se connecter",
    signUp: "S'inscrire",
    gptSearchPlaceholder: "Que voulez-vous regarder aujourd'hui ?",
    GPTSearch: "GPT Recherche",
    NowPlaying: "En cours de lecture",
    Popular: "Populaire",
    TopRated: "Mieux notés",
    Upcoming: "À venir",
    dontHaveAccount: "Vous n'avez pas de compte ? Inscrivez-vous",
    alreadyHaveAccount: "Vous avez déjà un compte ? Connectez-vous",
  },
  Arabic: {
    search: "بحث",
    home: "الصفحة الرئيسية",
    movies: "أفلام",
    shows: "برامج",
    popular: "شائع",
    trending: "اتجاهات",
    profile: "الملف الشخصي",
    settings: "الإعدادات",
    logout: "تسجيل الخروج",
    welcome: "أهلاً وسهلاً",
    play: "تشغيل",
    pause: "إيقاف مؤقت",
    watchNow: "شاهد الآن",
    signIn: "تسجيل الدخول",
    signUp: "التسجيل",
    gptSearchPlaceholder: "ماذا ترغب في مشاهدته اليوم؟",
    GPTSearch: "بحث GPT",
    NowPlaying: "الآن يعرض",
    Popular: "شائع",
    TopRated: "أفضل تقييم",
    Upcoming: "قريباً",
    dontHaveAccount: "لا تملك حساب؟ سجل",
    alreadyHaveAccount: "هل لديك حساب؟ سجل دخول",
  },
  Portuguese: {
    search: "buscar",
    home: "Início",
    movies: "Filmes",
    shows: "Programas",
    popular: "Popular",
    trending: "Tendências",
    profile: "Perfil",
    settings: "Configurações",
    logout: "Sair",
    welcome: "Bem-vindo",
    play: "Jogar",
    pause: "Pausa",
    watchNow: "Assistir agora",
    signIn: "Entrar",
    signUp: "Cadastrar-se",
    gptSearchPlaceholder: "O que você gostaria de assistir hoje?",
    GPTSearch: "Busca GPT",
    NowPlaying: "Agora tocando",
    Popular: "Popular",
    TopRated: "Mais bem avaliados",
    Upcoming: "Próximos",
    dontHaveAccount: "Não tem conta? Cadastre-se",
    alreadyHaveAccount: "Já tem uma conta? Entre",
  },
  Italian: {
    search: "cerca",
    home: "Home",
    movies: "Film",
    shows: "Programmi",
    popular: "Popolare",
    trending: "Tendenze",
    profile: "Profilo",
    settings: "Impostazioni",
    logout: "Esci",
    welcome: "Benvenuto",
    play: "Gioca",
    pause: "Pausa",
    watchNow: "Guarda ora",
    signIn: "Accedi",
    signUp: "Registrati",
    gptSearchPlaceholder: "Cosa ti piacerebbe guardare oggi?",
    GPTSearch: "Ricerca GPT",
    NowPlaying: "Ora in riproduzione",
    Popular: "Popolare",
    TopRated: "Valutato meglio",
    Upcoming: "In arrivo",
    dontHaveAccount: "Non hai un account? Registrati",
    alreadyHaveAccount: "Hai già un account? Accedi",
  },
  Japanese: {
    search: "検索",
    home: "ホーム",
    movies: "映画",
    shows: "ショー",
    popular: "人気",
    trending: "トレンド",
    profile: "プロフィール",
    settings: "設定",
    logout: "ログアウト",
    welcome: "ようこそ",
    play: "再生",
    pause: "一時停止",
    watchNow: "今すぐ見る",
    signIn: "サインイン",
    signUp: "サインアップ",
    gptSearchPlaceholder: "今日は何を見たいですか？",
    GPTSearch: "GPT検索",
    NowPlaying: "再生中",
    Popular: "人気",
    TopRated: "最高評価",
    Upcoming: "近日公開",
    dontHaveAccount: "アカウントをお持ちでないですか？サインアップ",
    alreadyHaveAccount: "すでにアカウントをお持ちですか？サインイン",
  },
  Korean: {
    search: "검색",
    home: "홈",
    movies: "영화",
    shows: "쇼",
    popular: "인기",
    trending: "트렌드",
    profile: "프로필",
    settings: "설정",
    logout: "로그아웃",
    welcome: "환영합니다",
    play: "재생",
    pause: "일시 정지",
    watchNow: "지금 보기",
    signIn: "로그인",
    signUp: "회원가입",
    gptSearchPlaceholder: "오늘 무엇을 보고 싶으세요?",
    GPTSearch: "GPT 검색",
    NowPlaying: "현재 상영 중",
    Popular: "인기",
    TopRated: "최고 평가",
    Upcoming: "예정",
    dontHaveAccount: "계정이 없으신가요? 가입하기",
    alreadyHaveAccount: "계정이 있으신가요? 로그인",
  },
  Turkish: {
    search: "ara",
    home: "Ana Sayfa",
    movies: "Filmler",
    shows: "Şovlar",
    popular: "Popüler",
    trending: "Trend",
    profile: "Profil",
    settings: "Ayarlar",
    logout: "Çıkış yap",
    welcome: "Hoş geldiniz",
    play: "Oynat",
    pause: "Duraklat",
    watchNow: "Şimdi izle",
    signIn: "Giriş yap",
    signUp: "Kayıt ol",
    gptSearchPlaceholder: "Bugün ne izlemek istersiniz?",
    GPTSearch: "GPT Arama",
    NowPlaying: "Şu an oynuyor",
    Popular: "Popüler",
    TopRated: "En yüksek puan",
    Upcoming: "Yaklaşan",
    dontHaveAccount: "Hesabınız yok mu? Kayıt ol",
    alreadyHaveAccount: "Zaten bir hesabınız var mı? Giriş yap",
  },
  Bengali: {
    search: "খোঁজ",
    home: "হোম",
    movies: "ফিল্ম",
    shows: "শো",
    popular: "জনপ্রিয়",
    trending: "ট্রেন্ডিং",
    profile: "প্রোফাইল",
    settings: "সেটিংস",
    logout: "লগ আউট",
    welcome: "স্বাগতম",
    play: "প্লে",
    pause: "পজ",
    watchNow: "এখন দেখুন",
    signIn: "সাইন ইন করুন",
    signUp: "সাইন আপ করুন",
    gptSearchPlaceholder: "আজ আপনি কি দেখতে চান?",
    GPTSearch: "জিপিটি সার্চ",
    NowPlaying: "এখন চলছে",
    Popular: "জনপ্রিয়",
    TopRated: "শীর্ষ রেটেড",
    Upcoming: "আসন্ন",
    dontHaveAccount: "অ্যাকাউন্ট নেই? সাইন আপ করুন",
    alreadyHaveAccount: "আগে থেকেই অ্যাকাউন্ট আছে? সাইন ইন করুন",
  },
};
export default language;
